### ISSUE TITLE
Link to the Tarmak pages?

### ISSUE THREAD

**Issue by DreymaR** [shelbyd/tarmak#9]
Hi! This is DreymaR from the Colemak forums.

I think it'd be nice if you link to the pages on Tarmak, showing where it came from and much more.

You even used a picture of my post without giving credit, which isn't entirely nice.

Maybe I'll throw in a link to your repo in return? :-)

https://forum.colemak.com/topic/1858-learn-colemak-in-steps-with-the-tarmak-layouts/

**Comment by shelbyd** [comment]
Send a PR and I'll happily review. I'm not working on this anymore, really. So I'll likely not do it myself.

**Comment by DreymaR** [comment]
Okay, I made an attempt and hope it's to your liking. It's my first pull request ever, so let me know if I did something wrong! :-)

**Comment by shelbyd** [comment]
Merged #10.
